import type { AppLabels } from "@/labels/types";

export const appLabels: AppLabels["app"] = {
  dashboard: {
    heading: "Dashboard",
    description: "Welcome back.",
    projectsHeading: "Projects",
    createProjectCta: "Create project",
    statusHeading: "Status",
    inspectCta: "Inspect",
    statuses: {
      draft: "Draft",
      inprogress: "In Progress",
      reviewed: "Reviewed",
      complete: "Complete",
      rejected: "Rejected",
    },
  },
  projectInspect: {
    heading: "Project",
    statusLabel: "Status",
    createdLabel: "Created",
    idLabel: "Project ID",
    copyIdAriaLabel: "Copy project ID",
    copySuccessToast: "Project ID copied to clipboard.",
    copyErrorToast: "Could not copy project ID.",
    deleteProjectCta: "Delete project",
    deleteProjectConfirm:
      "Delete this project? Files, diligence jobs, and findings will be removed permanently.",
    deleteProjectInProgress: "Deleting...",
    deleteProjectSuccessToast: "Project deleted.",
    deleteProjectErrorToast: "Failed to delete project.",
    documentsHeading: "Files",
    fileInputLabel: "Upload files",
    uploadInProgress: "Uploading...",
    dropzoneTitle: "Drag and drop files to upload",
    dropzoneHint: "Files upload automatically after drop.",
    uploadQueueHeading: "Upload progress",
    uploadStatusQueued: "queued",
    uploadStatusUploading: "uploading",
    uploadStatusUploaded: "uploaded",
    uploadStatusFailed: "failed",
    emptyDocuments: "No files uploaded yet.",
    loadingDocuments: "Loading files...",
    loadError: "Failed to load files.",
    uploadError: "Failed to upload file.",
    viewFileCta: "View",
    deleteFileCta: "Delete",
    deleteInProgress: "Deleting...",
    deleteError: "Failed to delete file.",
    reprocessFileCta: "Re-process",
    reprocessInProgress: "Queueing...",
    reprocessError: "Failed to queue file for re-processing.",
    fileStatusLabel: "File status",
    fileProcessingStatuses: {
      QUEUED: "queued",
      PROCESSING: "processing",
      PROCESSED: "processed",
      FAILED: "failed",
    },
    beDiligentCta: "Be Diligent",
    providerSelectionLabel: "Provider",
    modelInputLabel: "Model",
    modelInputPlaceholder: "gpt-4o-mini",
    fallbackProvidersLabel: "Fallback providers",
    retryDiligenceCta: "Retry diligence",
    cancelDiligenceCta: "Cancel diligence",
    cancelDiligenceConfirm: "Cancel the running diligence workflow?",
    cancelDiligenceToast: "Diligence cancelled.",
    cancelDiligenceErrorToast: "Failed to cancel diligence.",
    diligenceProgressHeading: "Diligence worker",
    diligenceStatusLabel: "Job status",
    diligenceCurrentStageLabel: "Current stage",
    diligenceJobIdLabel: "Job ID",
    diligenceTokenUsageLabel: "Token usage",
    diligenceCostEstimateLabel: "Estimated cost",
    diligenceLastErrorLabel: "Last error",
    diligenceNoJobMessage: "No diligence job has started yet.",
    diligenceJobCreatedToast: "Due diligence job initialized.",
    diligenceRunningToast: "Diligence workflow running.",
    diligenceCompletedToast: "Due diligence job completed.",
    diligenceRetryToast: "Diligence retry started.",
    diligenceRetryErrorToast: "Failed to retry due diligence.",
    diligenceStatuses: {
      QUEUED: "queued",
      RUNNING: "running",
      WAITING_INPUT: "waiting for input",
      COMPLETED: "completed",
      FAILED: "failed",
      CANCELED: "canceled",
    },
    diligenceStages: {
      DOCUMENT_EXTRACTION: "document extraction",
      DOCUMENT_CLASSIFICATION: "document classification",
      ENTITY_EXTRACTION: "entity extraction",
      CLAIM_EXTRACTION: "claim extraction",
      RISK_EXTRACTION: "risk extraction",
      CROSS_DOCUMENT_VALIDATION: "cross-document validation",
      CONTRADICTION_DETECTION: "contradiction detection",
      EVIDENCE_GRAPH_GENERATION: "evidence graph generation",
      EXECUTIVE_SUMMARY_GENERATION: "executive summary generation",
      FINAL_REPORT_GENERATION: "final report generation",
    },
    setupApiKeysMessage: "Add at least one API key in Settings to run due diligence.",
    setupApiKeysToast: "No API keys found. Opening Settings in a new tab.",
    diligenceStartToast: "Due diligence started.",
    insightsHeading: "Reviewed insights",
    insightsEmpty: "No reviewed insights yet. Run due diligence to generate findings.",
    insightsRisksHeading: "Top risks",
    insightsClaimsHeading: "Key claims",
    insightsEntitiesHeading: "Core entities",
    insightsContradictionsHeading: "Contradictions",
  },
  insights: {
    heading: "Insights",
    description: "All findings, claims, entities, and contradictions from the latest completed diligence run.",
    empty: "No insights available. Complete a diligence run to generate findings.",
    findingsHeading: "Findings",
    claimsHeading: "Claims",
    entitiesHeading: "Entities",
    contradictionsHeading: "Contradictions",
    jobInfoHeading: "Job summary",
    stagesHeading: "Pipeline stages",
    confidenceLabel: "Confidence",
    statusLabel: "Status",
    typeLabel: "Type",
    modelLabel: "Model",
    providerLabel: "Provider",
    tokensLabel: "Tokens",
    costLabel: "Est. cost",
    createdLabel: "Created",
    completedLabel: "Completed",
    findingTypes: {
      RISK: "Risk",
      OPPORTUNITY: "Opportunity",
      WARNING: "Warning",
      OBSERVATION: "Observation",
    },
    claimStatuses: {
      SUPPORTED: "Supported",
      CONTRADICTED: "Contradicted",
      INCONCLUSIVE: "Inconclusive",
    },
  },
  reports: {
    heading: "Reports",
    description: "Generated reports and export bundles from diligence runs.",
    empty: "No reports generated yet. Complete a diligence run to produce reports.",
    tableHeadType: "Type",
    tableHeadStage: "Stage",
    tableHeadFormat: "Format",
    tableHeadSize: "Size",
    tableHeadDate: "Generated",
    tableHeadJobStatus: "Job status",
    tableHeadActions: "Actions",
    viewCta: "View",
    artifactTypes: {
      GENERATED_REPORT: "Report",
      EXPORT_BUNDLE: "Export bundle",
      EVIDENCE_MAP: "Evidence map",
    },
  },
  projectCreation: {
    heading: "Create project",
    description: "Name your project to start qualification.",
    nameLabel: "Project name",
    namePlaceholder: "Acme diligence workspace",
    filesLabel: "Files",
    filesHint: "You can upload one or more files now.",
    submitCta: "Create project",
  },
};
