import type { AppLabels } from "@/labels/types";

export const appLabels: AppLabels["app"] = {
  dashboard: {
    heading: "Dashboard",
    description: "Welcome back.",
    projectsHeading: "Projects",
    createProjectCta: "Create project",
    statusHeading: "Status",
    inspectCta: "Inspect",
    statuses: {
      draft: "draft",
      inprogress: "in progress",
      complete: "complete",
      rejected: "rejected",
    },
  },
  projectInspect: {
    heading: "Project",
    statusLabel: "Status",
    createdLabel: "Created",
    idLabel: "Project ID",
    copyIdAriaLabel: "Copy project ID",
    copySuccessToast: "Project ID copied to clipboard.",
    copyErrorToast: "Could not copy project ID.",
    documentsHeading: "Files",
    fileInputLabel: "Upload files",
    uploadInProgress: "Uploading...",
    dropzoneTitle: "Drag and drop files to upload",
    dropzoneHint: "Files upload automatically after drop.",
    uploadQueueHeading: "Upload progress",
    uploadStatusQueued: "queued",
    uploadStatusUploading: "uploading",
    uploadStatusUploaded: "uploaded",
    uploadStatusFailed: "failed",
    emptyDocuments: "No files uploaded yet.",
    loadingDocuments: "Loading files...",
    loadError: "Failed to load files.",
    uploadError: "Failed to upload file.",
    viewFileCta: "View",
    deleteFileCta: "Delete",
    deleteInProgress: "Deleting...",
    deleteError: "Failed to delete file.",
    beDiligentCta: "Be Diligent",
    setupApiKeysMessage: "Add at least one API key in Settings to run due diligence.",
    setupApiKeysToast: "No API keys found. Opening Settings in a new tab.",
    diligenceStartToast: "Due diligence workflow start is coming next.",
  },
  projectCreation: {
    heading: "Create project",
    description: "Name your project and attach the source files to start qualification.",
    nameLabel: "Project name",
    namePlaceholder: "Acme diligence workspace",
    filesLabel: "Files",
    filesHint: "You can upload one or more files now.",
    submitCta: "Create project",
  },
};
